trad FR + update version mkdocs material
deadlock-resources/challenge-documentation pull request #10
Opened 2021-12-16 10:11 UTC by meitneshi

2021-12-16 11:40 UTC, Slayug requested changes

2021-12-16 11:40 UTC, Slayug commented on docs/index.md
C'est possible d'ajouter une partie expliquant ici que en premier temps le guide va expliquer ce qu'est une mission dîte *classique* mais que d'autres types d'exercices existent avec le lien vers la page des autres types d'exercices ?

2021-12-16 11:40 UTC, Slayug commented on docs/index.md
> +Le fichier `HelloWorld.java` dans le package `success` ne sera fourni à l'utilisateur que lorsqu'il aura réussi la mission.
```suggestion
*Le fichier `HelloWorld.java` dans le package `success` ne sera fourni à l'utilisateur que lorsqu'il aura réussi la mission.*
```

2021-12-16 11:40 UTC, Slayug commented on docs/index.md
> +Le code ci-dessus loggue une erreur et s'arrête avec un code d'erreur si la fonction `HelloWorld.sayHello()`
```suggestion
Le code ci-dessus logue une erreur et s'arrête avec un code d'erreur si la fonction `HelloWorld.sayHello()` 
```

https://la-conjugaison.nouvelobs.com/du/verbe/loguer.php

2021-12-16 11:40 UTC, Slayug commented on docs/index.md
> +2. Success : Le code compile, s'est terminé normalement et retourne le résultat attendu
```suggestion
2. Success : Le code compile, s'est terminé normalement et retourne le résultat attendu.
```

2021-12-16 11:40 UTC, Slayug commented on docs/index.md
> +La chaine de caractère que vous devez retourner n'est rien d'autre que les
```suggestion
La chaîne de caractère que vous devez retourner n'est rien d'autre que les 
```

2021-12-16 11:40 UTC, Slayug commented on docs/index.md
> +La chaine de caractère attendue est sensible à la casse, vous devriez essayer plusieurs casses.
```suggestion
La chaîne de caractère attendue est sensible à la casse, vous devriez essayer plusieurs casses.
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/vscode.md
> +Il est temps d'utiliser Deadlock dans le navigateur !
En vrai la formulation de base est incorrect, on utlise déjà Deadlock dans le navigateur aha

ça serait plutôt :  

```suggestion
Il est temps d'utiliser VsCode dans le navigateur !
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/vscode.md
>      crud: 9090
```suggestion
    crud: 9090 # la personne se verra attribuer une url qui redirigera vers le port 9090
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/vscode.md
> +Vous devez préfixer le path de votre image avec *image:*
```suggestion
Vous devez préfixer le path de votre image avec **image:**
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/vscode.md
>  ```Bash
ça serait bien d'ajouter un lien vers le début de la documentation si iels ont pas lu le début de la doc et sont directement arrivé.es ici

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/vscode.md
> +*Si vous avez besoin de remplir la base de données, il est préférable de le faire dans le Dockerfile (utiliser un script au démarrage est plus long) :*
```suggestion
*Si vous avez besoin de remplir la base de données, il est préférable de le faire dans le Dockerfile (utiliser un script au démarrage va allonger le démarrage du container) :*
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/metamorph.md
> +Imaginons que vous souhaitez écrire une mission d'implémentation de la suite de Fibonacci.
```suggestion
Imaginons que vous souhaitez écrire une mission d'implémentation de la suite de Fibonacci.  

```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/metamorph.md
> +- tous les tests pour valider le code du candidat.
```suggestion
Créer un nouveau dossier contenant un fichier `entry.rs`. Ce fichier définit : 

- quel(s) langage(s) sont disponibles pour l'implémentation de la résolution du candidat,
- tous les tests pour valider le code du candidat.  
```
Si il y a pas de breaking line, la liste est cassée et s'affiche en ligne

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/metamorph.md
> -```Java linenums="1" tab=
Le système de tabulation n'est plus présent (outil **Tabbed** https://facelessuser.github.io/pymdown-extensions/)

Regarde comment c'est affiché ici https://deadlock-resources.github.io/challenge-documentation/challenge-types/metamorph/

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/metamorph.md
> +L'utilisateur doit compléter la méthode `fibonacci` et le résultat sera afficher dans le stdout (console).
```suggestion
L'utilisateur doit compléter la méthode `fibonacci` et le résultat sera affiché dans le stdout (console).  
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/metamorph.md
> +Cela vous semble trop statique ?
Tu peux ajouter un titre juste avant genre # Aléatoire

Comme ça on pourra trouver cette partie plus facilement

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/metamorph.md
> +Il sera servi au candidat en tant que *Chaine de caractère*.
```suggestion
Il sera servi au candidat en tant que *Chaîne de caractère*.
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/score.md
> +Par exemple, si vous considérez que si 50 tests validés sur les 100 disponibles suffisent à conbsidérer la mission comme
```suggestion
Par exemple, si vous considérez que si 50 tests validés sur les 100 disponibles suffisent à considérer la mission comme 
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/score.md
>  ```Java tab=
Ici tu as bien laissé les tabulations :D

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/sql.md
> +Une mission SQL est une mission classique de code avec une base de donnée distante injecté via un service. Plus d'infos sur les [services](../multi-service)
```suggestion
Une mission SQL est une mission classique de code avec une base de donnée distante injectée via un service. Plus d'infos sur les [services](../multi-service)   
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/sql.md
> +* Comparer les deux réponses
```suggestion
Dans ce cas vous avez besoin de : 

* Exécuter la réponse attendue et stocker le résultat dans _**first !**_
* Exécuter la réponse du candidat et stocker le résultat dans _**only after !**_
* Comparer les deux réponses
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/sql.md
> +_Il est nécessaire exécuter votre réponse en premier afin d'éviter tout retour en arrière de la base de donnée que le code du candidat pourrait provoquer._
```suggestion
_Il est nécessaire d'exécuter votre réponse en premier afin d'éviter tout retour en arrière de la base de donnée que le code du candidat pourrait provoquer._
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/sql.md
> +Ce type de mission est un peu plus compliqué à valider. Elles débutent généralement pas :
```suggestion
Ce type de mission est un peu plus compliqué à valider. Elles débutent généralement par :  
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/sql.md
> +* Exécuter le script checker.sql et stocker le résultat
```suggestion
* Exécuter le script `checker.sql` et stocker le résultat
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/sql.md
> +* Exécuter le script checker.sql et stocker le résultat
```suggestion
* Exécuter le script `checker.sql` et stocker le résultat
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/sql.md
> +https://github.com/deadlock-resources/challenge-examples/tree/master/example/code_sql
```suggestion
[https://github.com/deadlock-resources/challenge-examples/tree/master/example/code_sql](https://github.com/deadlock-resources/challenge-examples/tree/master/example/code_sql)
```

2021-12-16 11:40 UTC, Slayug commented on docs/challenge-types/code.md
> +# Exemple de mission de code
```suggestion
# Exemples de mission de code
```

2021-12-16 11:40 UTC, Slayug commented on docs/mode/index.md
> +Vous pouvez également votre propre liste noire pour une mission en créant un fichier `blacklist` au même niveau que le challenge.yml
```suggestion
Vous pouvez également créer votre propre liste noire pour une mission en créant un fichier `blacklist` au même niveau que le challenge.yml
```

2021-12-16 11:40 UTC, Slayug commented on docs/mode/index.md
> +Un exemple est disponible dans `resources/default/blacklist`.
`resources/default/blacklist` ce truc est mystérieux si on ne connaît pas le repo deadlock-challenges, tu peux ajouter ce qu'il contient ici stp

2021-12-16 11:40 UTC, Slayug commented on docs/mode/index.md
> +Exemple de fichier blackilist :
```suggestion
Exemple de fichier blacklist :   
```

2021-12-16 11:40 UTC, Slayug commented on docs/how-does-it-work.md
> +Nous allons vous expliquer l'utilité de tous les fichiers d'une mission,
```suggestion
Nous allons vous expliquer l'utilité de tous les fichiers d'une mission.
```

2021-12-16 11:40 UTC, Slayug commented on docs/how-does-it-work.md
> +Si le **code de sortie** est **0**, la mission est un **succès"**.
```suggestion
Si le **code de sortie** est **0**, la mission est un **succès**.  
```

2021-12-16 11:40 UTC, Slayug commented on docs/contributing.md
Tu peux aussi ajouter ce lien https://git.e-biz.fr/deadlock-public en donnant une explication rapide

2021-12-16 13:51 UTC, meitneshi commented on docs/challenge-types/metamorph.md
> -```Java linenums="1" tab=
les tabulations restait sur la preview, j'ai remis les tab ici

2021-12-16 14:03 UTC, meitneshi commented on docs/challenge-types/vscode.md
>  ```Bash
arrivé à cette partie ou a cette page ? savoir si je met le lien en haut de fichier ou a l'endroit que tu mentionne

2021-12-17 06:34 UTC, Slayug requested changes

2021-12-17 06:34 UTC, Slayug commented on docs/challenge-types/vscode.md
>  ```Bash
oui ça peut être bien de le mettre au début comme  ça sera plus simple à retrouver, genre après le `Vous voulez que vos étudiants puisse profiter d'un éditeur` quelque chose du style, `assurez-vous d'abord le dcli d'installer etc`

2021-12-17 06:34 UTC, Slayug commented on docs/challenge-types/metamorph.md
> -```Java linenums="1" tab=
les templates sont cassés maintenant, je pense que ça vient de l'ajout de `* Template Javascript` avant chaque ligne

![image](https://user-images.githubusercontent.com/1078777/146499505-bd9dde20-fc9f-48bf-a2e9-40ae96936ba9.png)

2021-12-17 10:34 UTC, meitneshi commented on docs/challenge-types/vscode.md
>  ```Bash
done

2021-12-20 14:00 UTC, Slayug requested changes

2021-12-22 09:13 UTC, merged